Added "Send password reset email" button to backend users update page
wintercms/winter pull request #723
Opened 2022-10-02 10:04 UTC by prsuhas

2022-10-02 20:40 UTC, LukeTowers requested changes

2022-10-02 20:40 UTC, LukeTowers commented on modules/backend/controllers/users/_btn_password_reset.php
> +</div>
```suggestion
</div>

```

2022-10-02 20:40 UTC, LukeTowers commented on modules/backend/controllers/users/_btn_password_reset.php
> +        data-load-indicator="<?= e(trans('backend::lang.account.working')) ?>"
```suggestion
        data-load-indicator="<?= e(trans('backend::lang.account.sending')) ?>"
```

2022-10-02 20:40 UTC, LukeTowers commented on modules/backend/lang/en/lang.php
> +        'working' => 'Working...',
```suggestion
        'sending' => 'Sending...',
```

2022-10-02 20:40 UTC, LukeTowers commented on modules/backend/lang/en/lang.php
> +        'manual_password_reset_confirm' => 'Are you sure you want to send password reset mail for this user?',
```suggestion
        'manual_password_reset_confirm' => 'Are you sure you want to send a password reset email to this user?',
```

2022-10-02 20:40 UTC, LukeTowers commented on modules/backend/lang/en/lang.php
> +        'manual_password_reset_success' => 'An email has been sent to user with reset instructions.',
```suggestion
        'manual_password_reset_success' => 'An email has been sent to the user with instructions to reset their password.',
```

2022-10-02 20:40 UTC, LukeTowers commented on modules/backend/controllers/Users.php
> +        //@todo::Force Trusted Host verification
```suggestion
```

2022-10-02 20:40 UTC, LukeTowers approved these changes

2022-10-02 20:41 UTC, LukeTowers commented
@prsuhas no, that's fine, we can leave the code copy-pasted for now. Can you add a screenshot of what the new button looks like please?

2022-10-03 04:30 UTC, prsuhas commented
> @prsuhas no, that's fine, we can leave the code copy-pasted for now. Can you add a screenshot of what the new button looks like please?

Please find below screenshot

![Screenshot from 2022-10-03 09-53-54](https://user-images.githubusercontent.com/66815373/193501881-30509541-cd18-4c50-a45c-d1830aa90af3.png)

Pushed the review changes too.

2022-10-13 09:35 UTC, merged